baseURL = 'http://example.org/'
languageCode = 'fr-fr'
title = 'PortFolio de Pablo Djezzy'
theme = 'iutdelens'

[[menu.main]]
    name = "À propos"
    url = "/a-propos-de"

[[menu.main]]
    name = "Blog"
    url = "/blog"

[[menu.social]]
    name = "GitHub"
    url = "https://github.com/VotreCompteGithub"
    pre = "<i class='fab fa-github'></i>"

[[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/VotreCompteTwitter"
    pre = "<i class='fab fa-twitter'></i>"

[[menu.footer]]
    name = "À propos"
    url = "/a-propos-de"

[params]
    author = "Moi"
    authorImage = "/images/moi.jpg"